import {
  Home, CreditCard, Users, BarChart3, Package, ShoppingCart, ClipboardList, Truck,
  Briefcase, Hammer, PieChart, FolderOpen, MessageSquare, Store, GraduationCap,
  Building2, Wrench, Key, Cloud, ShieldAlert, ShoppingBag, Cpu, Sparkles,
} from 'lucide-react';
import { Globe as StorefrontIcon } from 'lucide-react';
import type { AppDefinition, SwitcherFolder } from './types';

export const SEGMENT_NAMES: Record<string, string> = {
  apps: 'Apps',
  crm: 'CRM',
  finance: 'Finance',
  hr: 'HR',
  inventory: 'Inventory',
  procurement: 'Procurement',
  projects: 'Projects',
  manufacturing: 'Manufacturing',
  pos: 'POS',
  communication: 'Connect',
  connect: 'Connect',
  drive: 'Drive',
  analytics: 'Analytics',
  settings: 'Settings',
  profile: 'Profile',
  builder: 'Studio',
  build: 'Build',
  manage: 'Manage',
  releases: 'Releases',
  logs: 'Run Logs',
  access: 'Access Control',
  connectors: 'Connectors',
  marketplace: 'Marketplace',
  'query-builder': 'Query Builder',
  widgets: 'Widget SDK',
  git: 'Git Control',
  'mobile-export': 'Export & Mobile',
  collections: 'CMS Collections',
  submissions: 'Form Submissions',
  store: 'App Store',
  'real-estate': 'Real Estate',
  healthcare: 'Healthcare',
  education: 'Education',
  'field-service': 'Field Service',
  saas: 'SaaS',
  security: 'Security',
  'security-policies': 'Security Policies',
  'compliance-governance': 'Compliance & Governance',
  'approval-operations': 'Approval Operations',
  'workflow-builder': 'Workflow Builder',
  'branding-communication': 'Branding & Communication',
  'system-operations': 'System Operations',
  'general-branding': 'General & Branding',
  'api-platform': 'API Platform',
  'api-key-whitelists': 'API Key Whitelists',
  'api-integration-hub': 'API Integration Hub',
  'i18n-localization': 'i18n Localization',
  'sync-monitor': 'Sync Monitor',
  'devops-telemetry': 'DevOps & Telemetry',
  'marketing-outreach': 'Marketing & Outreach',
  'sales-enablement': 'Sales Enablement',
  'account-plans': 'Account Plans',
  'cpq': 'CPQ Pricing',
  'fulfillment': 'Fulfillment',
  'sla': 'SLA Analytics',
  'operations-service': 'Operations & Service',
  operations: 'Operations',
  customers: 'Customers',
  vendors: 'Vendors',
  contacts: 'Contacts',
  contracts: 'Contracts',
  cases: 'Cases & SLA',
  leads: 'Leads',
  opportunities: 'Opportunities',
  quotations: 'Quotations',
  reports: 'Reports',
  'sales-orders': 'Sales Orders',
  activities: 'Activities',
  'email-templates': 'Email Templates',
  advanced: 'Advanced',
  segments: 'Segments',
  'duplicate-rules': 'Duplicate Rules',
  pipelines: 'Pipelines',
  'sla-policies': 'SLA Policies',
  'email-integration': 'Email Integration',
  'purchase-orders': 'Purchase Orders',
  'purchase-receipts': 'Purchase Receipts',
  returns: 'Returns',
  rfqs: 'RFQs',
  'supplier-quotations': 'Supplier Quotations',
  'delivery-notes': 'Delivery Notes',
  orders: 'Orders',
  'client-portal': 'Client Portal',
  health: 'Strategic Health',
  portfolios: 'Portfolios',
  workloads: 'Workloads',
  'revenue-recognition': 'Revenue Recognition',
  boms: 'BOMs',
  configurator: 'Configurator',
  diagnostics: 'Diagnostics',
  mrp: 'MRP',
  quality: 'Quality',
  scheduling: 'Scheduling',
  'shop-floor': 'Shop Floor',
  designer: 'Receipt Designer',
  'ap-automation': 'AP Automation',
  'ar-automation': 'AR Automation',
  'bank-accounts': 'Bank Accounts',
  'bank-feeds': 'Bank Connections',
  'bank-recon': 'Bank Reconciliation',
  'cash-flow-forecast': 'Cash Flow Forecast',
  'intercompany': 'Intercompany',
  'netting': 'Netting',
  'eliminations': 'Eliminations',
  'fx-revaluation': 'FX Revaluation',
  'payment-terms': 'Payment Terms',
  'invoice-analytics': 'Invoice Analytics',
  'tax-filing-summary': 'Tax Filing Summary',
  'ar-aging': 'AR Aging Report',
  'customer-statement': 'Customer Statement',
  'credit-risk': 'Credit Risk Management',
  ai: 'AI Copilot',
  'forecast-scenarios': 'Rolling Forecasts (xP&A)',
  'accounting-books': 'Accounting Books',
  budgeting: 'Budgeting',
  'chart-of-accounts': 'Chart of Accounts',
  'financial-periods': 'Financial Periods',
  'fixed-assets': 'Fixed Assets',
  'journal-entries': 'Journal Entries',
  'tax-engine': 'Tax Engine',
  'tax-filing': 'Tax Filing',
  treasury: 'Treasury',
  appraisals: 'Appraisals',
  assets: 'Assets',
  attendance: 'Attendance',
  benefits: 'Benefits',
  compliance: 'Compliance',
  feedback: 'Feedback',
  goals: 'Goals',
  holidays: 'Holidays',
  leaves: 'Leaves',
  offboarding: 'Offboarding',
  onboarding: 'Onboarding',
  payroll: 'Payroll',
  positions: 'Positions',
  recruitment: 'Recruitment',
  'self-service': 'Self-Service',
  shifts: 'Shifts',
  skills: 'Skills',
  succession: 'Succession',
  surveys: 'Surveys',
  tickets: 'Tickets',
  trainings: 'Trainings',
  batches: 'Batches',
  'bin-locations': 'Bin Locations',
  'cycle-counts': 'Cycle Counts',
  'qa-inspections': 'QA Inspections',
  'serial-numbers': 'Serial Numbers',
  'stock-entries': 'Stock Entries',
  'stock-ledger': 'Stock Ledger',
  'stock-levels': 'Stock Levels',
  valuations: 'Valuations',
  warehouses: 'Warehouses',
  escalations: 'Escalations',
  simulation: 'Simulation',
  requisitions: 'Requisitions',
  'blanket-agreements': 'Blanket Agreements',
  portal: 'Supplier Portal',
  'super-admin': 'Super Admin',
  'access-control': 'Access Control',
  tenants: 'Tenants',
  admins: 'Admin Users',
  'activity-feed': 'Activity Feed',
  announcements: 'Announcements',
  'scheduled-reports': 'Scheduled Reports',
  notifications: 'Notifications',
  'import-export': 'Import / Export',
  gdpr: 'GDPR',
  workflows: 'Workflows',
  templates: 'Templates',
  quotas: 'Storage Quotas',
  media: 'Media Conversion',
  groups: 'User Groups',
  mfa: 'MFA Settings',
  'password-policy': 'Password Policies',
  sessions: 'Sessions',
  impersonate: 'Impersonate User',
  'ip-restrictions': 'IP Restrictions',
  'audit-trail': 'Audit Trail',
  'login-history': 'Login History',
  'data-retention': 'Data Retention',
  'login-customizer': 'Login Customizer',
  'email-config': 'SMTP Server',
  maintenance: 'Maintenance Mode',
  'system-health': 'System Health',
  jobs: 'Background Jobs',
  'scheduled-tasks': 'Scheduled Tasks',
  'error-logs': 'Error Logs',
  backups: 'Database Backups',
  'db-schema': 'Database Schema',
  modules: 'Module Manager',
  'feature-flags': 'Feature Flags',
  domains: 'Custom Domains',
  environments: 'Environments',
  updates: 'System Updates',
  'tenant-analytics': 'Tenant Analytics',
  bulk: 'Bulk Approvals',
  routing: 'Dynamic Routing',
  email: 'Email Approvals',
  general: 'General Settings',
  branding: 'Branding & Appearance',
  integrations: 'Integrations',
  import: 'Import Data',
  export: 'Export Data',
  erasure: 'GDPR Erasure',
  retention: 'GDPR Retention',
  webhooks: 'Webhooks Configuration',
  'webhook-logs': 'Webhook Logs',
  oauth: 'SSO & OAuth',
  sandbox: 'Developer Sandbox',
  roles: 'User Roles',
  packages: 'Access Packages',
  matrix: 'Permissions Matrix',
  'identity-access': 'Identity & Access',
  ecommerce: 'E-Commerce',
  listings: 'Listings',
  intelligence: 'Intelligence',
  'lead-scoring': 'Lead Scoring',
  'deal-velocity': 'Deal Velocity',
  clv: 'CLV Analytics',
  partners: 'Partner Management',
  journey: 'Attribution & Journey',
  sentiment: 'Sentiment & Health',
  campaigns: 'Campaign Analytics',
};

export const formatSegment = (segment: string): string => {
  const name = SEGMENT_NAMES[segment.toLowerCase()];
  if (name) {
    return name;
  }
  return segment
    .split(/[-_]/)
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
};

/**
 * Every top-level application known to the shell. `installed: false` apps are
 * industry modules that only appear in the switcher once installed for a tenant.
 */
export const allApplications: AppDefinition[] = [
  { id: 'dashboard', name: 'Dashboard', href: '/dashboard', icon: Home, installed: true },
  { id: 'finance', name: 'Finance & Accounting', href: '/finance', icon: CreditCard, installed: true },
  { id: 'hr', name: 'Human Resources', href: '/hr', icon: Users, installed: true },
  { id: 'crm', name: 'CRM & Sales', href: '/crm', icon: BarChart3, installed: true },
  { id: 'inventory', name: 'Inventory & Stock', href: '/inventory', icon: Package, installed: true },
  { id: 'procurement', name: 'Procurement', href: '/procurement', icon: ShoppingCart, installed: true },
  { id: 'sales', name: 'Sales & Orders', href: '/sales', icon: ClipboardList, installed: true },
  { id: 'supply-chain', name: 'Supply Chain', href: '/supply-chain', icon: Truck, installed: true },
  { id: 'projects', name: 'Project Management', href: '/projects', icon: Briefcase, installed: true },
  { id: 'manufacturing', name: 'Manufacturing', href: '/manufacturing', icon: Hammer, installed: true },
  { id: 'analytics', name: 'Business Intelligence', href: '/analytics', icon: PieChart, installed: true },
  { id: 'ai', name: 'AI Copilot', href: '/ai', icon: Sparkles, installed: true },
  { id: 'drive', name: 'Drive', href: '/drive', icon: FolderOpen, installed: true },
  { id: 'communication', name: 'Connect', href: '/connect', icon: MessageSquare, installed: true },
  { id: 'pos', name: 'POS & Retail', href: '/pos', icon: Store, installed: true },
  { id: 'ecommerce', name: 'E-Commerce', href: '/ecommerce', icon: StorefrontIcon, installed: true },
  { id: 'education', name: 'Education Module', href: '/education', icon: GraduationCap, installed: false },
  { id: 'real-estate', name: 'Real Estate Module', href: '/real-estate', icon: Building2, installed: false },
  { id: 'field-service', name: 'Field Service Module', href: '/field-service', icon: Wrench, installed: false },
  { id: 'api-keys', name: 'API Platform', href: '/settings/api-keys', icon: Key, installed: true },
  { id: 'saas', name: 'SaaS Portal', href: '/saas/portal', icon: Cloud, installed: true },
  { id: 'app-store', name: 'App Store', href: '/apps/store', icon: ShoppingBag, installed: true },
  { id: 'builder', name: 'Studio', href: '/builder', icon: Cpu, installed: true },
];

export const switcherFolders: SwitcherFolder[] = [
  {
    id: 'developer',
    name: 'Developer',
    color: '#334155',
    appIds: ['api-keys', 'app-store', 'builder', 'saas'],
  },
];

/**
 * Kernel apps are always present (never uninstallable); every other app shows
 * only when it's installed for the tenant.
 */
export const KERNEL_APP_IDS = new Set(['dashboard', 'api-keys', 'saas', 'app-store', 'builder', 'ai']);
